server:
  shutdown: immediate
  port: 8081

spring:
  application:
    name: order-service
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/mydb?useSSL=false&serverTimezone=UTC
    username: root
    password: 1234
  jpa:
    show-sql: true
    generate-ddl: false
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        format_sql: true
    open-in-view: false
  data:
    redis:
      host: localhost
      port: 6379
  jackson:
    time-zone: UTC
  docker:
    compose:
      lifecycle-management:

management:
  endpoint:
    health:
      show-details: always
    web:
      exposure:
        include: '*'


logging:
  level:
    root: info
    org.springframework.web: INFO
    com.yutsuki.order_service: DEBUG
    org.springframework.web.servlet: DEBUG
    org.hibernate.engine.transaction.internal.TransactionImpl: DEBUG
    org.hibernate.orm.jdbc.bind: TRACE
